---
project_name: "monasca"

monasca_services:
  monasca-api:
    container_name: monasca_api
    group: monasca
    enabled: true
    image: "{{ monasca_api_image_full }}"
    volumes:
      - "{{ node_config_directory }}/monasca/:{{ container_config_directory }}/:ro"
  monasca-log:
    container_name: monasca_log_api
    group: monasca
    enabled: true
    image: "{{ monasca_log_api_image_full }}"
    volumes:
      - "{{ node_config_directory }}/monasca/:{{ container_config_directory }}/:ro"
  monasca-notification:
    container_name: monasca_notification
    group: monasca
    enabled: true
    image: "{{ monasca_notification_image_full }}"
    volumes:
      - "{{ node_config_directory }}/monasca/:{{ container_config_directory }}/:ro"
  monasca-persister:
    container_name: monasca_persister
    group: monasca
    enabled: true
    image: "{{ monasca_persister_image_full }}"
    volumes:
      - "{{ node_config_directory }}/monasca/:{{ container_config_directory }}/:ro"
  monasca-statsd:
    container_name: monasca_statsd
    group: monasca
    enabled: true
    image: "{{ monasca_statsd_image_full }}"
    volumes:
      - "{{ node_config_directory }}/monasca/:{{ container_config_directory }}/:ro"


####################
# Docker
####################
monasca_install_type: "{{ kolla_install_type }}"
monasca_tag: "{{ openstack_release }}"

monasca_api_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ monasca_install_type }}-monasca-api"
monasca_api_tag: "{{ monasca_tag }}"
monasca_api_image_full: "{{ monasca_api_image }}:{{ monasca_api_tag }}"

monasca_log_api_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ monasca_install_type }}-monasca-log-api"
monasca_log_api_tag: "{{ monasca_tag }}"
monasca_log_api_image_full: "{{ monasca_log_api_image }}:{{ monasca_log_api_tag }}"

monasca_notification_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ monasca_install_type }}-monasca-notification"
monasca_notification_tag: "{{ monasca_tag }}"
monasca_notification_image_full: "{{ monasca_notification_image }}:{{ monasca_notification_tag }}"

monasca_persister_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ monasca_install_type }}-monasca-persister"
monasca_persister_tag: "{{ monasca_tag }}"
monasca_persister_image_full: "{{ monasca_persister_image }}:{{ monasca_persister_tag }}"

monasca_statsd_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ monasca_install_type }}-monasca-statsd"
monasca_statsd_tag: "{{ monasca_tag }}"
monasca_statsd_image_full: "{{ monasca_statsd_image }}:{{ monasca_statsd_tag }}"
