---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ monasca_services }}"

- name: Copying over config.json files for services
  vars:
    service_name: "monasca"
    service: "{{ monasca_services[service_name] }}"
  template:
    src: "{{ service_name }}.json.j2"
    dest: "{{ node_config_directory }}/{{ service_name }}/config.json"
    mode: "0660"
  become: true
  register: monasca_config_json
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - restart monasca

- name: Check monasca containers
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
  become: true
  register: check_monasca_containers
  when:
    - action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ monasca_services }}"
  notify:
    - restart monasca
