---
- name: restart monasca
  vars:
    service_name: "monasca"
    service: "{{ monasca_services[service_name] }}"
    monasca_container: "{{ check_monasca_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
  when:
    - action != "config"
    - inventory_hostname != master_host
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - monasca_config_json.changed | bool
      or monasca_container.changed | bool
  notify:
    - wait for monasca

- name: wait for monasca
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ monasca_port }}"
    connect_timeout: 1
    timeout: 60
    search_regex: "Monasca"
  register: check_monasca_port
  until: check_monasca_port | success
  retries: 10
  delay: 6
  when:
    - action != "config"
